./configure bugfix

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -24,13 +24,34 @@ function check {
   fi
 }
 
+function checkNoParam {
+  bin="$1"
+  ver="$2"
+  binPath=`which $bin`
+  if [[ `$binPath 2>&1` =~ $ver ]]; then
+    echo "$bin has been verified!"
+    echo "$bin,$binPath">>$configFile
+  else
+    echo "No compatible version of $bin found. Please enter path:"
+    read binPath
+    if [[ `$binPath 2>&1` =~ $ver ]]; then
+      echo "$bin has been verified!"
+      echo "$bin,$binPath">>$configFile
+    else
+      echo "ERROR: No compatible version of $bin found!"
+      exit 1
+    fi
+  fi
+}
+
+
 check Rscript "version 3"
 check blastn "blastn: 2.2" "-version"
 check bowtie2 "version 2"
 check qstat "SGE 6|OGS/GE 2011" "-help"
 # check java "version \"1.7" "-version"
-check samtools "Version: 0.1.19" ""
-check bcftools "Version: 0.1.19" ""
+checkNoParam samtools "Version: 0.1.19"
+checkNoParam bcftools "Version: 0.1.19"
 
 
 # echo "Please enter the absolute path to SNVerIndividual.jar:"
